-- DESABILITAR RLS TEMPORARIAMENTE
-- Execute AGORA para restaurar acesso completo

ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;

SELECT 'RLS DESABILITADO - ACESSO TOTAL RESTAURADO' as status;

